import type { Player } from '@/types/domain';

/** Fábrica de Player para tests: defaults completos + overrides parciales. */
export function makePlayer(partial: Partial<Player> = {}): Player {
  return {
    id: 'p1',
    coach_id: 'c1',
    auth_user_id: null,
    invite_code: 'CAMPO01',
    name: 'Jugador Test',
    pos: 'Mediocentro',
    pos_group: 'Medio',
    age: 18,
    foot: 'Derecho',
    club: 'CAMPO FC',
    category: null,
    status: 'available',
    trend: 'eq',
    score: 70,
    adherence: 80,
    mins: 100,
    callups: 5,
    played: 4,
    scored: 2,
    assisted: 1,
    sleep: null,
    tag: null,
    height_cm: null,
    weight_kg: null,
    vertical_jump: null,
    horizontal_jump: null,
    flexibility_cmj: null,
    rm_squat: null,
    rm_deadlift: null,
    rm_bench: null,
    ai_attributes: null,
    ai_metrics: null,
    strength: null,
    improve: null,
    demo: false,
    photo_url: null,
    created_at: '2026-05-25T00:00:00Z',
    ...partial,
  };
}
